### PR TITLE
Fix links in README

### PR DESCRIPTION
**Pull request by fcamblor**

### CODE REVIEW

**Comment by jnizet** [comment]
Thanks Frédéric!

**Comment by fcamblor** [comment]
mmmm ... doesn't fixes "this file" link .. let me see ...

**Comment by fcamblor** [comment]
Seems like omitting `tree/master/` in the URL is OK (defaulting to `master` branch) :  
`examples/src/main/kotlin/com/ninjasquad/springrestdocskotlin/examples`
is resolved to
`tree/master/examples/src/main/kotlin/com/ninjasquad/springrestdocskotlin/examples`

But for a BLOB, I guess we need to explicitely but the `blob/<branch>` thing in the URL :  
`examples/src/main/kotlin/com/ninjasquad/springrestdocskotlin/examples/ExtensionFunctionsExampleTest.kt`
should become
`blob/master/examples/src/main/kotlin/com/ninjasquad/springrestdocskotlin/examples/ExtensionFunctionsExampleTest.kt`

Yikes :/

**Comment by fcamblor** [comment]
Forget what I've said ... all good (I guess I got trapped by an outdated `README.MD`)

**Pull request merged**
